# Generated by Django 5.2.6 on 2025-09-28 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('twofa_secret', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'app_user',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('decimals', models.IntegerField()),
                ('is_crypto', models.BooleanField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('country', models.TextField(blank=True, null=True)),
                ('timezone', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'exchange',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('action', models.TextField()),
                ('target_type', models.TextField(blank=True, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.appuser')),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='base_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.currency'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('class_field', models.TextField(db_column='class')),
                ('symbol', models.TextField()),
                ('name', models.TextField()),
                ('isin', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('trading_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.currency')),
                ('exchange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.exchange')),
            ],
            options={
                'db_table': 'asset',
                'unique_together': {('symbol', 'exchange')},
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('settings', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.appuser')),
            ],
            options={
                'db_table': 'portfolio',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('message', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.portfolio')),
            ],
            options={
                'db_table': 'advice',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tx_type', models.TextField()),
                ('tx_time', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=38)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('fee', models.DecimalField(decimal_places=10, max_digits=38)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.asset')),
                ('linked_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.transaction')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.portfolio')),
                ('price_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.currency')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='AssetIdentifier',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('id_type', models.TextField()),
                ('id_value', models.TextField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.asset')),
            ],
            options={
                'db_table': 'asset_identifier',
                'unique_together': {('asset', 'id_type'), ('id_type', 'id_value')},
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=10, max_digits=38)),
                ('source', models.TextField()),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.currency')),
                ('quote_currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fxrate_quote_currency_set', to='api.currency')),
            ],
            options={
                'db_table': 'fx_rate',
                'unique_together': {('base_currency', 'quote_currency', 'ts', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('provider', models.TextField()),
                ('display_name', models.TextField()),
                ('status', models.TextField()),
                ('credentials_encrypted', models.TextField()),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.appuser')),
            ],
            options={
                'db_table': 'integration',
                'unique_together': {('user', 'provider', 'display_name')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=38)),
                ('source', models.TextField()),
                ('interval', models.TextField()),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.asset')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.currency')),
            ],
            options={
                'db_table': 'price',
                'unique_together': {('asset', 'ts', 'source', 'interval')},
            },
        ),
    ]
