# Generated by Django 5.2.6 on 2026-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_add_portfolio_transactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioasset",
            name="avg_buy_price",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="portfolioasset",
            name="buy_currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
