# Generated by Django 5.2.6 on 2025-12-20 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_name_alter_asset_symbol'),
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioasset',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset'),
        ),
    ]
