# Generated by Django 5.2.7 on 2025-10-26 22:18

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('provider', models.TextField()),
                ('display_name', models.TextField()),
                ('status', models.TextField(default='active')),
                ('credentials_encrypted', models.TextField()),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'integrations"."integration',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('provider_code', models.TextField()),
                ('ext_account_id', models.TextField()),
                ('display_name', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('integration', models.ForeignKey(db_column='integration_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='integrations.integration')),
            ],
            options={
                'db_table': 'integrations"."account',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountPortfolio',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('instrument_types', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('venue_codes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('symbols_include', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('symbols_exclude', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, null=True, size=None)),
                ('is_primary', models.BooleanField(default=True)),
                ('account', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_links', to='integrations.account')),
                ('portfolio', models.ForeignKey(db_column='portfolio_id', on_delete=django.db.models.deletion.CASCADE, related_name='integration_accounts', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'integrations"."account_portfolio',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('account', 'portfolio'), name='account_portfolio_account_id_portfolio_id_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='integration',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'display_name'), name='integration_user_id_provider_display_name_key'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('integration', 'ext_account_id'), name='account_integration_id_ext_account_id_key'),
        ),
    ]
