# Generated by Django 5.2.6 on 2026-01-27 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE SCHEMA IF NOT EXISTS llm;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='LLMChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('GENERAL', 'General'), ('PORTFOLIO_ANALYSIS', 'Portfolio analysis'), ('RISK_REVIEW', 'Risk review'), ('PERFORMANCE_REVIEW', 'Performance review'), ('MARKET_TRENDS', 'Market trends')], default='GENERAL', max_length=32)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"llm"."llm_chat"',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_text', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_snapshots', to='llm.llmchat')),
            ],
            options={
                'db_table': '"llm"."llm_context_snapshot"',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(default='gpt-5.2-chat-latest', max_length=128)),
                ('provider', models.CharField(default='proxyapi', max_length=64)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.2, max_digits=3)),
                ('max_context_tokens_per_request', models.PositiveIntegerField(default=20000)),
                ('max_output_tokens', models.PositiveIntegerField(default=4096)),
                ('context_window_tokens', models.PositiveIntegerField(default=128000)),
                ('system_prompt', models.TextField(blank=True, default='')),
                ('context_mode', models.CharField(choices=[('FULL', 'Full'), ('COMPACT', 'Compact'), ('OFF', 'Off')], default='COMPACT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='llm.llmchat')),
            ],
            options={
                'db_table': '"llm"."llm_chat_settings"',
            },
        ),
        migrations.CreateModel(
            name='LLMMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', 'System'), ('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('error', 'Error')], default='completed', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('total_tokens', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='llm.llmchat')),
            ],
            options={
                'db_table': '"llm"."llm_message"',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('MESSAGE', 'Message'), ('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='MESSAGE', max_length=16)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=64)),
                ('model_id', models.CharField(blank=True, default='', max_length=128)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('context_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llm.llmchat')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='llm.llmmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_token_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"llm"."llm_token_usage"',
            },
        ),
        migrations.AddIndex(
            model_name='llmchat',
            index=models.Index(fields=['user', 'updated_at'], name='llm_chat_user_id_2fe0e6_idx'),
        ),
        migrations.AddIndex(
            model_name='llmmessage',
            index=models.Index(fields=['chat', 'created_at'], name='llm_message_chat_id_87808d_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['user', 'usage_type', 'period_start'], name='llm_token_u_user_id_70afdb_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusage',
            index=models.Index(fields=['chat', 'created_at'], name='llm_token_u_chat_id_38b449_idx'),
        ),
        migrations.AddConstraint(
            model_name='tokenusage',
            constraint=models.UniqueConstraint(condition=models.Q(('usage_type__in', ['DAILY', 'MONTHLY'])), fields=('user', 'usage_type', 'period_start'), name='llm_token_usage_unique_period'),
        ),
    ]
