# Generated by Django 5.2.7 on 2025-10-26 20:56

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_enums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('decimals', models.IntegerField(default=2)),
                ('is_crypto', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market"."currency',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market"."exchange',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('asset_class', apps.core.models.AssetClassEnumField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('fund', 'Fund'), ('crypto', 'Crypto'), ('fiat', 'Fiat'), ('metal', 'Metal'), ('cash', 'Cash'), ('deposit', 'Deposit'), ('other', 'Other')], db_column='class', enum_name='core.asset_class_enum')),
                ('symbol', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=255)),
                ('isin', models.CharField(blank=True, max_length=32, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trading_currency', models.ForeignKey(blank=True, db_column='trading_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='market.currency')),
                ('exchange', models.ForeignKey(blank=True, db_column='exchange_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='market.exchange')),
            ],
            options={
                'db_table': 'market"."asset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=10, max_digits=38)),
                ('source', models.CharField(max_length=64)),
                ('base_currency', models.ForeignKey(db_column='base_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='fx_base', to='market.currency')),
                ('quote_currency', models.ForeignKey(db_column='quote_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='fx_quote', to='market.currency')),
            ],
            options={
                'db_table': 'market"."fx_rate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=38)),
                ('source', models.CharField(max_length=64)),
                ('interval', apps.core.models.PriceIntervalEnumField(choices=[('tick', 'Tick'), ('min', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], db_column='interval', default='day', enum_name='core.price_interval_enum')),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market.asset')),
                ('currency', models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='market.currency')),
            ],
            options={
                'db_table': 'market"."price',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AssetIdentifier',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('id_type', models.CharField(max_length=64)),
                ('id_value', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='market.asset')),
            ],
            options={
                'db_table': 'market"."asset_identifier',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('asset', 'id_type'), name='ux_asset_identifier_asset_id_type'), models.UniqueConstraint(fields=('id_type', 'id_value'), name='ux_asset_identifier_type_value')],
            },
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('symbol', 'exchange'), name='ux_market_asset_symbol_exchange'),
        ),
        migrations.AddIndex(
            model_name='fxrate',
            index=models.Index(fields=['base_currency', 'quote_currency', '-ts'], name='ix_market_fx_pair_ts'),
        ),
        migrations.AddConstraint(
            model_name='fxrate',
            constraint=models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'ts', 'source'), name='ux_fx_pair_ts_source'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['asset', '-ts'], name='ix_market_price_asset_ts'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['source'], name='ix_market_price_source'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('asset', 'ts', 'source', 'interval'), name='ux_price_asset_ts_source_interval'),
        ),
    ]
