# Generated by Django 5.2.7 on 2025-10-27 18:32

import apps.core.models
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tag_type', models.TextField()),
                ('tag_value', models.TextField()),
            ],
            options={
                'db_table': 'market"."asset_tag',
            },
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('interval', apps.core.models.PriceIntervalEnumField(choices=[('tick', 'Tick'), ('min', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], db_column='interval', enum_name='core.price_interval_enum')),
                ('open', models.DecimalField(decimal_places=10, max_digits=38)),
                ('high', models.DecimalField(decimal_places=10, max_digits=38)),
                ('low', models.DecimalField(decimal_places=10, max_digits=38)),
                ('close', models.DecimalField(decimal_places=10, max_digits=38)),
                ('volume', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True)),
                ('trades_count', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market"."bar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('split', 'Split'), ('merge', 'Merge'), ('symbol_change', 'Symbol change'), ('delisting', 'Delisting'), ('spin_off', 'Spin-off')], max_length=32)),
                ('ex_date', models.DateField()),
                ('ratio', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'market"."corporate_action',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField()),
                ('bid', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('ask', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('mid', models.GeneratedField(db_persist=True, expression=models.Case(models.When(ask__isnull=False, bid__isnull=False, then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('bid'), '+', models.F('ask')), '/', models.Value(2))), models.When(bid__isnull=False, then=models.F('bid')), models.When(ask__isnull=False, then=models.F('ask')), default=None, output_field=models.DecimalField(decimal_places=10, max_digits=38)), null=True, output_field=models.DecimalField(decimal_places=10, max_digits=38))),
                ('depth', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market"."quote',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='fxrate',
            name='provider',
            field=models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_rates', related_query_name='fx_rate', to='marketdata.provider'),
        ),
        migrations.AddField(
            model_name='price',
            name='provider',
            field=models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_prices', related_query_name='price', to='marketdata.provider'),
        ),
        migrations.AddIndex(
            model_name='fxrate',
            index=models.Index(fields=['provider'], name='ix_market_fx_provider'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['provider'], name='ix_market_price_provider'),
        ),
        migrations.AddField(
            model_name='assettag',
            name='asset',
            field=models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='market.asset'),
        ),
        migrations.AddField(
            model_name='bar',
            name='asset',
            field=models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='bars', to='market.asset'),
        ),
        migrations.AddField(
            model_name='bar',
            name='currency',
            field=models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='bars', to='market.currency'),
        ),
        migrations.AddField(
            model_name='bar',
            name='provider',
            field=models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bars', to='marketdata.provider'),
        ),
        migrations.AddField(
            model_name='corporateaction',
            name='asset',
            field=models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.PROTECT, related_name='corporate_actions', to='market.asset'),
        ),
        migrations.AddField(
            model_name='quote',
            name='asset',
            field=models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='market.asset'),
        ),
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.ForeignKey(db_column='currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='market.currency'),
        ),
        migrations.AddField(
            model_name='quote',
            name='provider',
            field=models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='marketdata.provider'),
        ),
        migrations.AddConstraint(
            model_name='assettag',
            constraint=models.UniqueConstraint(fields=('asset', 'tag_type', 'tag_value'), name='ux_asset_tag'),
        ),
        migrations.AddIndex(
            model_name='bar',
            index=models.Index(fields=['asset', '-ts'], name='ix_bar_asset_ts'),
        ),
        migrations.AddIndex(
            model_name='bar',
            index=models.Index(fields=['provider'], name='ix_bar_provider'),
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.CheckConstraint(condition=models.Q(('low__lte', models.F('open')), ('low__lte', models.F('close')), ('high__gte', models.F('open')), ('high__gte', models.F('close')), ('low__lte', models.F('high'))), name='bar_ohlc_check'),
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.UniqueConstraint(condition=models.Q(('provider__isnull', True)), fields=('asset', 'ts', 'interval'), name='uq_bar_no_provider'),
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.UniqueConstraint(condition=models.Q(('provider__isnull', False)), fields=('asset', 'ts', 'interval', 'provider'), name='uq_bar_with_provider'),
        ),
        migrations.AddIndex(
            model_name='corporateaction',
            index=models.Index(fields=['asset', 'ex_date'], name='ix_ca_asset_exdate'),
        ),
        migrations.AddConstraint(
            model_name='corporateaction',
            constraint=models.CheckConstraint(condition=models.Q(('action_type__in', ('split', 'merge', 'symbol_change', 'delisting', 'spin_off'))), name='corporate_action_action_type_check'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['asset', '-ts'], name='ix_quote_asset_ts'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['provider'], name='ix_quote_provider'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.CheckConstraint(condition=models.Q(('bid__isnull', True), ('ask__isnull', True), ('bid__lte', models.F('ask')), _connector='OR'), name='quote_bid_ask_check'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('provider__isnull', True)), fields=('asset', 'ts'), name='uq_quote_no_provider'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(condition=models.Q(('provider__isnull', False)), fields=('asset', 'ts', 'provider'), name='uq_quote_with_provider'),
        ),
    ]
