# Generated by Django 5.2.7 on 2025-10-26 19:43

from django.db import migrations

SCHEMAS = ["account","analytics","integrations","llm","market","marketdata","portfolio"]

SQL = [
    "CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;",
    "CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;",
    'CREATE SCHEMA IF NOT EXISTS "core";',
] + [f'CREATE SCHEMA IF NOT EXISTS "{s}";' for s in SCHEMAS]

class Migration(migrations.Migration):
    initial = True
    dependencies = [
    ]
    operations = [migrations.RunSQL(sql, reverse_sql="") for sql in SQL]
