# Generated by Django 5.2.7 on 2025-10-26 19:45

from django.db import migrations

CREATE_ENUMS = r"""
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace
    WHERE t.typname='asset_class_enum' AND n.nspname='core'
  ) THEN
    CREATE TYPE core.asset_class_enum AS ENUM
      ('stock','bond','fund','crypto','fiat','metal','cash','deposit','other');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace
    WHERE t.typname='transaction_type_enum' AND n.nspname='core'
  ) THEN
    CREATE TYPE core.transaction_type_enum AS ENUM
      ('buy','sell','deposit','withdraw','transfer_in','transfer_out',
       'dividend','coupon','interest','fee','split','merge','adjustment');
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid=t.typnamespace
    WHERE t.typname='price_interval_enum' AND n.nspname='core'
  ) THEN
    CREATE TYPE core.price_interval_enum AS ENUM ('tick','min','hour','day');
  END IF;
END$$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_extensions_and_schemas'),
    ]

    operations = [migrations.RunSQL(CREATE_ENUMS, reverse_sql="")]
