# Generated by Django 5.2.7 on 2025-10-26 20:26

# apps/account/migrations/0001_user_state.py
from django.db import migrations, models
import django.contrib.auth.models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    # atomic=False не обязательно, но можно оставить по вкусу
    atomic = False

    operations = [
        # Объявляем swappable-модель User для миграционного состояния,
        # НО managed=False — БД-таблица создана ранее, Django её не трогает.
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150, blank=True)),
                ('last_name', models.CharField(max_length=150, blank=True)),
                ('email', models.EmailField(max_length=254, blank=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'account"."auth_user',
                'managed': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        # Добавляем M2M к группам/правам — эти ПРОМЕЖУТОЧНЫЕ таблицы будут СОЗДАНЫ Django
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(
                to='auth.group',
                related_name='user_set',
                related_query_name='user',
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(
                to='auth.permission',
                related_name='user_set',
                related_query_name='user',
                blank=True,
            ),
        ),
    ]
