# Generated by Django 5.2.6 on 2026-01-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
