# Generated by Django 5.2.6 on 2026-01-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_schema_and_table_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
