# Generated by Django 5.2.6 on 2025-12-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_name_alter_asset_symbol'),
        ('assets', '0004_seed_assets'),
    ]

    operations = [
    ]
