# Generated by Django 5.2.7 on 2025-10-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('as_of', models.DateTimeField()),
                ('total_value', models.DecimalField(decimal_places=10, max_digits=38)),
                ('pnl_1d', models.DecimalField(decimal_places=10, max_digits=38)),
                ('pnl_7d', models.DecimalField(decimal_places=10, max_digits=38)),
                ('pnl_30d', models.DecimalField(decimal_places=10, max_digits=38)),
                ('portfolio', models.ForeignKey(db_column='portfolio_id', on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'analytics"."portfolio_snapshot',
                'managed': True,
                'indexes': [models.Index(fields=['portfolio', '-as_of'], name='ix_an_port_snap_port_date')],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'as_of'), name='portfolio_snapshot_portfolio_id_as_of_key')],
            },
        ),
        migrations.CreateModel(
            name='PositionValuationDaily',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('as_of', models.DateField()),
                ('qty', models.DecimalField(decimal_places=18, max_digits=38)),
                ('price', models.DecimalField(decimal_places=10, max_digits=38)),
                ('fx_to_base', models.DecimalField(decimal_places=10, max_digits=38)),
                ('value_base', models.DecimalField(decimal_places=10, max_digits=38)),
                ('cost_basis_base', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('realized_pnl_base', models.DecimalField(decimal_places=10, default=0, max_digits=38)),
                ('unrealized_pnl_base', models.DecimalField(decimal_places=10, default=0, max_digits=38)),
                ('income_acc_base', models.DecimalField(decimal_places=10, default=0, max_digits=38)),
                ('metadata', models.JSONField(default=dict)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.PROTECT, related_name='valuations_daily', to='market.asset')),
                ('portfolio', models.ForeignKey(db_column='portfolio_id', on_delete=django.db.models.deletion.CASCADE, related_name='valuations_daily', to='portfolio.portfolio')),
                ('price_currency', models.ForeignKey(db_column='price_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='valuations_daily_prices', to='market.currency')),
            ],
            options={
                'db_table': 'analytics"."position_valuation_daily',
                'managed': True,
                'indexes': [models.Index(fields=['portfolio', '-as_of'], name='ix_an_posval_port_date'), models.Index(fields=['asset', '-as_of'], name='ix_an_posval_asset_date')],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'asset', 'as_of'), name='position_valuation_daily_portfolio_id_asset_id_as_of_key')],
            },
        ),
    ]
