# Generated by Django 5.2.7 on 2025-10-28 10:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.TextField()),
                ('message', models.TextField()),
                ('score', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('portfolio', models.ForeignKey(db_column='portfolio_id', on_delete=django.db.models.deletion.CASCADE, related_name='advices', to='portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Совет (LLM)',
                'verbose_name_plural': 'Советы (LLM)',
                'db_table': 'llm"."advice',
                'ordering': ['-created_at'],
            },
        ),
    ]
