# Generated by Django 5.2.7 on 2025-10-26 21:04

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(db_column='base_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='portfolios', to='market.currency')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'portfolio"."portfolio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=18, default=0, max_digits=38)),
                ('cost_basis', models.DecimalField(decimal_places=10, default=0, max_digits=38)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_positions', to='market.asset')),
                ('portfolio', models.ForeignKey(db_column='portfolio_id', on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.portfolio')),
            ],
            options={
                'db_table': 'portfolio"."position',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('tx_type', apps.core.models.TransactionTypeEnumField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('dividend', 'Dividend'), ('coupon', 'Coupon'), ('interest', 'Interest'), ('fee', 'Fee'), ('split', 'Split'), ('merge', 'Merge'), ('adjustment', 'Adjustment')], db_column='tx_type', enum_name='core.transaction_type_enum')),
                ('tx_time', models.DateTimeField(db_column='tx_time')),
                ('quantity', models.DecimalField(decimal_places=18, default=0, max_digits=38)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=38, null=True)),
                ('fee', models.DecimalField(decimal_places=10, default=0, max_digits=38)),
                ('notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(db_column='asset_id', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='market.asset')),
                ('linked_tx', models.ForeignKey(blank=True, db_column='linked_tx_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_children', to='portfolio.transaction')),
                ('portfolio', models.ForeignKey(db_column='portfolio_id', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.portfolio')),
                ('price_currency', models.ForeignKey(blank=True, db_column='price_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='priced_transactions', to='market.currency')),
            ],
            options={
                'db_table': 'portfolio"."transaction',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='portfolio',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='portfolio_user_id_name_key'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('portfolio', 'asset'), name='position_portfolio_id_asset_id_key'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['asset', '-tx_time'], name='ix_portfolio_tx_asset_time'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['portfolio', '-tx_time'], name='ix_portfolio_tx_portfolio_time'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['tx_type'], name='ix_portfolio_tx_type'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('price__isnull', True), ('price_currency__isnull', True)), models.Q(('price__isnull', False), ('price_currency__isnull', False)), _connector='OR'), name='transaction_check'),
        ),
    ]
