# Generated by Django 5.2.7 on 2025-10-27 17:59

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField(unique=True)),
                ('kind', models.TextField()),
                ('sla', models.TextField(blank=True, null=True)),
                ('cost', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'marketdata"."provider',
            },
        ),
        migrations.CreateModel(
            name='SymbolMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_symbol', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('valid_from', models.DateField(default=datetime.date(1970, 1, 1))),
                ('valid_to', models.DateField(default=datetime.date(9999, 12, 31))),
                ('asset', models.ForeignKey(blank=True, db_column='asset_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='symbol_maps', to='assets.asset')),
                ('exchange', models.ForeignKey(blank=True, db_column='exchange_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symbol_maps', to='assets.exchange', to_field='code')),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, related_name='symbol_maps', to='marketdata.provider')),
            ],
            options={
                'db_table': 'marketdata"."symbol_map',
                'indexes': [models.Index(fields=['provider', 'external_symbol'], name='ix_symbol_map_provider_symbol')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_from__lte', models.F('valid_to'))), name='ck_symbol_map_valid'), models.UniqueConstraint(fields=('provider', 'external_symbol', 'exchange'), name='ux_symbol_map')],
            },
        ),
    ]
