# Generated by Django 5.2.6 on 2026-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="price_currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
