# Generated by Django 5.2.6 on 2025-12-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Вручную'), ('INTEGRATION', 'Интеграция')], default='MANUAL', max_length=20),
        ),
    ]
