# Generated by Django 5.2.6 on 2026-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_add_transaction_price_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
