# Generated by Django 5.2.6 on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0004_schema_and_table_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="integration_dedupe_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "integration_dedupe_key"),
                name="tx_integration_dedupe_unique",
            ),
        ),
    ]
