# Generated by Django 5.2.6 on 2026-01-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_add_integration_dedupe_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('deposit', 'Депозит'), ('withdrawal', 'Вывод'), ('conversion', 'Конвертация'), ('futures_buy', 'Фьючерсы: покупка'), ('futures_sell', 'Фьючерсы: продажа')], max_length=20),
        ),
    ]
