# Generated by Django 5.2.6 on 2025-12-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('capital_start', models.DecimalField(decimal_places=8, max_digits=20)),
                ('capital_end', models.DecimalField(decimal_places=8, max_digits=20)),
                ('net_flow', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('pnl_day', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-snapshot_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'snapshot_date'), name='unique_daily_snapshot_per_portfolio')],
            },
        ),
    ]
