# Generated by Django 5.2.6 on 2026-01-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('portfolio', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAssetDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('snapshot', models.DecimalField(decimal_places=8, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=8, max_digits=20)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_daily_snapshots_by_type', to='assets.assettype')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_type_daily_snapshot', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-snapshot_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'asset_type', 'snapshot_date'), name='portfolio_asset_type_day_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='PortfolioDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('capital', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('margin', models.DecimalField(decimal_places=8, max_digits=20)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-snapshot_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'snapshot_date'), name='portfolio_day_snapshot')],
            },
        ),
    ]
