# Generated by Django 5.2.6 on 2025-12-20 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('assets', '0006_alter_asset_market_url_alter_asset_name'),
        ('portfolio', '0003_rename_update_at_portfolioasset_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioAssetDailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('snapshot', models.DecimalField(decimal_places=8, max_digits=20)),
                ('margin', models.DecimalField(decimal_places=8, max_digits=20)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_daily_snapshots_by_type', to='assets.assettype')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_type_daily_snapshot', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-snapshot_date', '-id'],
                'constraints': [models.UniqueConstraint(fields=('portfolio', 'asset_type', 'snapshot_date'), name='uniq_portfolio_asset_type_day')],
            },
        ),
    ]
