# Generated by Codex on 2026-02-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_asset_symbol_asset_type_unique"),
        ("portfolio", "0003_add_portfolio_asset_price_fields"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioValuationDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_date", models.DateField()),
                ("base_currency", models.CharField(max_length=10)),
                ("value_base", models.DecimalField(decimal_places=8, max_digits=20)),
                ("net_flow_base", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("pnl_base", models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="valuation_daily", to="portfolio.portfolio")),
            ],
        ),
        migrations.CreateModel(
            name="PortfolioPositionDaily",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("snapshot_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("price_base", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("value_base", models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="assets.asset")),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="position_daily", to="portfolio.portfolio")),
            ],
        ),
        migrations.AddConstraint(
            model_name="portfoliovaluationdaily",
            constraint=models.UniqueConstraint(fields=("portfolio", "snapshot_date"), name="portfolio_valuation_daily_unique"),
        ),
        migrations.AddConstraint(
            model_name="portfoliopositiondaily",
            constraint=models.UniqueConstraint(fields=("portfolio", "asset", "snapshot_date"), name="portfolio_position_daily_unique"),
        ),
    ]

